<?php
/**
 * @file
 * Creates a new blank page for your Drupal site
 */

function blank_page_help($path, $arg) {
  switch($path) {
    // Main help page
    case 'admin/help#blank_page':
      return '<p>' . t('The blank page module presents a form for creating '
              . 'a blank page. When the form is filled out and submitted, '
              . 'a new page will be created in the database with no content '
              . 'on the page.') . '</p>';
  }  
}

// Form for creating new page
function blank_page_form($node, &$form_state) {
  // Title of new page
  $form['new_title'] = array(
    '#type' => 'textfield',
    '#title' => t('New Page Title'),
    //'#maxlength' => 50,
  );
  
  // Submit Button
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#form' => 'new_title',
  );
  
  
  return $form;
}

// Validate form input before creating new page
function blank_page_form_validate($form, &$form_state) {
  $title = $form_state['values']['new_title'];
    
  // Ensure title is 50 characters or shorter
  if(strlen($title) > 50){
    form_set_error('title', 'Page title is too long. Please choose a shoter one');
  }
}

// Process form details
function blank_page_form_submit($form, &$form_state) {
  drupal_set_message('Calling submission type: ' 
          . $form['submit']['#form'] . '.');
  
  switch($form['submit']['#form']) {
    case 'new_title' :
      drupal_set_message('Successfully got to the new page creation in'
              . 'response area!');
      break;
  }
}

// Create administration page
function blank_page_menu() {
  $items = array();
    
  $items['admin/content/blank_page'] = array(
    'title' => 'Create a blank page',
    'description' => 'Filling out and submitting this form will allow'
      . ' you to create a blank page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('blank_page_form'),
    'access arguments' => array('administer nodes'),
    'type'=>MENU_NORMAL_ITEM, // TODO: What is this?
  );
  $items['admin/content/blank_page/test_tab'] = array(
      'title' => 'Test Tab',
      'description' => 'Tab just to test functionality.',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -10,
  );
  $items['admin/content/blank_page/test_tab2'] = array(
      'title' => 'Test Tab 2',
      'description' => 'Another tab just to test functionality.',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -5,
  );      
  
  return $items;
}



