<?php
/**
 * @file
 * Creates a new blank page for your Drupal site
 */

function blank_page_help($path, $arg) {
  switch($path) {
    // Main help page
    case 'admin/help#blank_page':
      return '<p>' . t('The blank page module presents a form for creating '
              . 'a blank page. When the form is filled out and submitted, '
              . 'a new page will be created in the database with no content '
              . 'on the page.') . '</p>';
  }  
}

// Form for creating new page
function blank_page_form($node, &$form_state) {
  // Create list of form items
  $form = array();

  
  $form['new_title'] = array(
    '#type' => 'textfield',
    '#title' => t('New Page Title'),
    '#maxlength' => 50,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  
  return $form;
}

// Validate form input before creating new page
function blank_page_form_validate($form, &$form_state) {
    
}

// Process form details
function blank_page_form_submit($form, &$form_state) {
    switch($form_state['values']['form_id']) {
        
    }
}

// Create administration page
function blank_page_menu() {
  $items = array();
    
  $items['admin/content/blank_page'] = array(
    'title' => 'Create a blank page',
    'description' => 'Filling out and submitting this form will allow'
      . ' you to create a blank page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('blank_page_form'),
    'access arguments' => array('administer nodes'),
    'type'=>MENU_NORMAL_ITEM, // TODO: What is this?
  );
  $items['admin/content/blank_page/test_tab'] = array(
      'title' => 'Test Tab',
      'description' => 'Tab just to test functionality.',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -10,
  );
  $items['admin/content/blank_page/test_tab2'] = array(
      'title' => 'Test Tab 2',
      'description' => 'Another tab just to test functionality.',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -5,
  );      
  
  return $items;
}



